# -*- coding: utf-8 -*-
"""BEFORE DATA CLEANSING/RAW DATA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v7C74YwcfhODc5TLEtjweP50XahWzfuM

# STEP 1: Select Datasets

# Path for CL datasets
"""

path_cl_2012 = '/content/drive/MyDrive/Colab Notebooks/cl_2012.xlsx' # This is the path where the files are located

path_cl_2013 = '/content/drive/MyDrive/Colab Notebooks/cl_2013.xlsx' # This is the path where the files are located

path_cl_2014 = '/content/drive/MyDrive/Colab Notebooks/cl_2014.xlsx' # This is the path where the files are located

"""# Step 2 : Uploading Datasets to Google Drive and import the libraries"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

"""# Step 3 : Read the files making conection between google drive and google colab"""

# Path for CL Datasets

path_cl_2012 = '/content/drive/MyDrive/Colab Notebooks/cl_2012.xlsx' # This is the path where the files are located
path_cl_2013 = '/content/drive/MyDrive/Colab Notebooks/cl_2013.xlsx' # This is the path where the files are located
path_cl_2014 = '/content/drive/MyDrive/Colab Notebooks/cl_2014.xlsx' # This is the path where the files are located

df_cl_2012 = pd.read_excel(path_cl_2012)
df_cl_2013 = pd.read_excel(path_cl_2013)
df_cl_2014 = pd.read_excel(path_cl_2014)

"""# security Copy"""

df_cl_1 = df_cl_2012.copy(deep = True)
df_cl_2 = df_cl_2013.copy(deep = True)
df_cl_3 = df_cl_2014.copy(deep = True)

"""# Step 4 :DATA INSPECTION
Normalizing names for every column name for every CL Dataset. First create the dictionaries for every table. There are three dictionaries because the 2013/14 Dataset has different column name for the field fuel type and the

#**Concatenate all the tables from CL and called it CL Union**
"""

df_cl_1.info()

df_cl_2.info()

df_cl_3.info()

Dictionary_2012 = {'lib_mrq':'brand', 'lib_mod_doss':'Model_file', 'lib_mod':'Model_UTAC',
                   'dscom':'Commercial_name', 'cnit':'Code_National_Identification_Type',
                   'tvv':'Type_Variante_Version(TVV)','typ_cbr':'fuel_type',
                   'hybride':'Hybride','puiss_admin_98':'Administrative_power','puiss_max':'power_maximal (kW)','typ_boite_nb_rapp':'Gearbox',
                   'conso_urb':'Urban_consumption (l/100km)',
                   'conso_exurb':'Extra_urban_consumption(l/100km)','conso_mixte':'Consumption_mix(l/100km)',
                   'co2':'CO2','co_typ_1':'CO_type_I (g/km)',
                   'hc':'hc','nox':'nox',
                   'hcnox':'hcnox','ptcl':'Particles', 'masse_ordma_min':'Empty_mass_min(kg)',
                   'masse_ordma_max':'Empty_mass_max(kg)',
                   'champ_v9':'Champ_V9','date_maj':'Missing_data','Carosserie':'Carosserie',
                   'gamme':'range'}


Dictionary_2013 = {'Marque':'brand','Modèle dossier':'Model_file', 'Modèle UTAC':'Model_UTAC',
                   'Désignation commerciale':'Commercial_name', 'CNIT':'Code_National_Identification_Type',
                   'Type Variante Version (TVV)':'Type_Variante_Version(TVV)','Carburant':'fuel_type',
                   'Hybride':'Hybride','Puissance administrative':'Administrative_power','Puissance maximale (kW)':'power_maximal (kW)','Boîte de vitesse':'Gearbox',
                   'Consommation urbaine (l/100km)':'Urban_consumption (l/100km)',
                   'Consommation extra-urbaine (l/100km)':'Extra_urban_consumption(l/100km)','Consommation mixte (l/100km)':'Consumption_mix(l/100km)',
                   'CO2 (g/km)':'CO2','CO type I (g/km)':'CO_type_I (g/km)',
                   'hc':'hc','nox':'nox',
                   'hcnox':'hcnox','Particules (g/km)':'Particles', 'masse vide euro min (kg)':'Empty_mass_min(kg)',
                   'masse vide euro max (kg)':'Empty_mass_max(kg)',
                   'Champ V9':'Champ_V9','Date de mise à jour':'Missing_data','Carosserie':'Carosserie',
                   'gamme':'range'}





Dictionary_2014 = {'lib_mrq':'brand','lib_mod_doss':'Model_file', 'lib_mod':'Model_UTAC',
                   'dscom':'Commercial_name', 'cnit':'Code_National_Identification_Type',
                   'tvv':'Type_Variante_Version(TVV)','cod_cbr':'fuel_type',
                   'hybride':'Hybride','puiss_admin_98':'Administrative_power','puiss_max':'power_maximal (kW)','typ_boite_nb_rapp':'Gearbox',
                   'conso_urb':'Urban_consumption (l/100km)',
                   'conso_exurb':'Extra_urban_consumption(l/100km)','conso_mixte':'Consumption_mix(l/100km)',
                   'co2':'CO2','co_typ_1':'CO_type_I (g/km)',
                   'hc':'hc','nox':'nox',
                   'hcnox':'hcnox','ptcl':'Particles', 'masse_ordma_min':'Empty_mass_min(kg)',
                   'masse_ordma_max':'Empty_mass_max(kg)',
                   'champ_v9':'Champ_V9','date_maj':'Missing_data','Carosserie':'Carosserie',
                   'gamme':'range'}


df_cl_1 = df_cl_1.rename(Dictionary_2012, axis = 1)
df_cl_2 = df_cl_2.rename(Dictionary_2013, axis = 1)
df_cl_3 = df_cl_3.rename(Dictionary_2014, axis = 1)

cl_union = pd.concat([df_cl_1,df_cl_2,df_cl_3], axis = 0) #Table that represents the total data from 2012 to 2014


cl_union.info()

cl_union.isnull().sum().sort_values(ascending = False)*100/len(cl_union)

cl_union.head()

"""### **CHECKING MISSING VALUES**"""

display(cl_union.isna().sum())

cl_union.duplicated().sum()

cl_union.isna().any(axis=1).count()

"""## Summary Statistics: Use .describe() to get a summary of the data, including mean, median, min, max, and quartiles, which can help identify outliers and data inconsistencies.

"""

cl_union.describe()

print("Column names and data types in the DataFrame:")
print(cl_union.dtypes)

"""## Graph of top 20 cars with highest Co2 emissions"""

filtered_df = cl_union[['brand', 'Model_file', 'Model_UTAC', 'Commercial_name', 'CO2']].dropna(subset=['CO2'])

# Sort the data by CO2 emissions in descending order and take the top 20
top_cars = filtered_df.sort_values(by='CO2', ascending=False).head(20)

# Combine brand and commercial name for better labels
top_cars['Car'] = top_cars['brand'] + " " + top_cars['Commercial_name']

# Create a horizontal bar plot of CO2 emissions by car model
plt.figure(figsize=(12, 8))
plt.barh(top_cars['Car'], top_cars['CO2'], color='skyblue')
plt.xlabel('CO2 Emissions (g/km)')
plt.ylabel('Car Model')
plt.title('Top 20 Cars with Highest CO2 Emissions')
plt.gca().invert_yaxis()  # Invert y-axis to have the highest CO2 emissions at the top

# Highlight the car with the highest CO2 emissions
max_co2 = top_cars['CO2'].max()
max_co2_car = top_cars[top_cars['CO2'] == max_co2]['Car'].values[0]
plt.barh(max_co2_car, max_co2, color='red')

# Show the plot
plt.tight_layout()
plt.show()

"""### **Standardizing THE DATA CL_UNION FROM COLUMN FUEL TYPE**

# ** Filling the Fuel Mode Fields according to the values from Fuel type and to fill in the blanks spaces later.
"""

def categorize_fuel_mode(fuel_type):

    if fuel_type =='EL':

        return 'Electric'

    elif fuel_type == 'GP':

        return 'Liquified_Petroleum_Gas'

    elif fuel_type == 'FE':
        return 'Superethanol_E85'

    elif fuel_type == 'ES':
        return 'Petrol_95'

    elif fuel_type == 'GO':
        return 'Diesel'

    elif  fuel_type == 'GP/ES':
        return 'Dual_fuel_petrol/Liquified_Petroleum_Gas'

    elif  fuel_type  == 'EE':
        return 'Hybrid_Petrol/Electric_plug_in'

    elif  fuel_type  == 'ES/GP':
        return 'Dual_fuel_petrol/Liquified_Petroleum_Gas'

    elif  fuel_type  == 'nan':
        return'NaN'

    elif fuel_type == 'GN':
        return 'Single_fuel_Natural_Gas'

    elif  fuel_type == 'GN/ES':
        return 'Dual_fuel_petrol/Natural_Gas'

    elif  fuel_type == 'ES/GN':
        return 'Dual_fuel_petrol/Natural_Gas'

    elif  fuel_type =='EH':
        return 'Hybrid_Petrol/Electric_non_plug_in'

    elif  fuel_type == 'GH':
        return 'Hybrid_Diesel/Electric_non_plug_in'


    elif fuel_type == 'GL':
        return 'Hybrid_Diesel/Electric_plug_in'

    else:
        return 'Diesel'

cl_union['fuel_mode'] = cl_union['fuel_type'].apply(categorize_fuel_mode)
cl_union['fuel_mode'] = cl_union['fuel_mode'].fillna(cl_union['fuel_mode'].mode()[0]) # fill blank with mode



cl_union['fuel_mode'].unique()

cl_union['fuel_type'].replace({'EL':'Electric', 'GP':'Liquified_Petroleum_Gas', 'FE':'Superethanol_E85', 'ES':'Petrol_95',
       'GO':'Diesel', 'GH':'Hybrid_Diesel/Electric_non_plug_in','EH':'Hybrid_Petrol/Electric_non_plug_in', 'GP/ES':'Dual_fuel_petrol/Liquified_Petroleum_Gas', 'EE':'Hybrid_Petrol/Electric_plug_in', 'ES/GP':'Dual_fuel_petrol/Liquified_Petroleum_Gas',
       'GN':'Single_fuel_Natural_Gas', 'GL': 'Hybrid_Diesel/Electric_plug_in','OTHER':'Other','GN/ES':'Dual_fuel_petrol/Natural_Gas','ES/GN':'Dual_fuel_petrol/Natural_Gas' },inplace = True) #To normalize the names of the types of Fuel


sns.heatmap(pd.crosstab(cl_union['fuel_type'], cl_union['fuel_mode'],margins=True, margins_name= 'Totals',normalize = True, dropna = False),cmap="YlGnBu", annot=True, cbar=True);
plt.title('Fuel Type versus Fuel Mode for Autos -Normalize Data-');
plt.xlabel('fuel Mode');
plt.ylabel('Fuel Type');

"""### **MATRIX CORRELATION and Heatmap to determine/visualize important variables**

### **Analysing target variable**
"""

# Correct column names based on the provided variables
columns = [
    'brand', 'Model_file', 'Model_UTAC', 'Commercial_name', 'Code_National_Identification_Type',
    'Type_Variante_Version(TVV)', 'fuel_type', 'Hybride', 'Administrative_power', 'power_maximal (kW)',
    'Gearbox', 'Urban_consumption (l/100km)', 'Extra_urban_consumption(l/100km)', 'Consumption_mix(l/100km)',
    'CO2', 'CO_type_I (g/km)', 'hc', 'nox', 'hcnox',
    'Particles', 'Empty_mass_min(kg)', 'Empty_mass_max(kg)', 'Champ_V9', 'Missing_data',
    'Carrosserie', 'range'
]

# Ensure the columns exist in the DataFrame
columns = [col for col in columns if col in cl_union.columns]

# Select relevant variables and drop rows with missing CO2 values
filtered_df = cl_union[columns].dropna(subset=['CO2'])

# Ensure no duplicate columns exist in filtered_df
assert filtered_df.columns.duplicated().sum() == 0, "There are still duplicate columns in filtered_df"

# Step 1: Identify the car that emits the most CO2 emissions
max_co2 = filtered_df['CO2'].max()
max_co2_car = filtered_df[filtered_df['CO2'] == max_co2]

print("Car with the highest CO2 emissions:")
print(max_co2_car[['brand', 'Model_file', 'Commercial_name', 'CO2']])

# Step 2: Analyze correlations between CO2 emissions and other numerical variables
numerical_columns = [
    'CO2', 'Administrative_power', 'power_maximal (kW)', 'Urban_consumption (l/100km)',
    'Extra_urban_consumption(l/100km)', 'Consumption_mix(l/100km)', 'CO_type_I (g/km)',
    'Hydrocarbon', 'nitrogen oxides', 'hydrocarbon and nitrogen oxides', 'Particles (g/km)',
    'Empty_mass_min(kg)', 'Empty_mass_max(kg)', 'range'
]

# Ensure the numerical columns exist in the DataFrame
numerical_columns = [col for col in numerical_columns if col in filtered_df.columns]

# Step 3: Create a scatter plot matrix to visualize relationships between CO2 and other variables
sns.pairplot(filtered_df[numerical_columns])
plt.suptitle('Scatter Plot Matrix of CO2 and Related Variables', y=1.02)
plt.show()


# Print the correlation matrix to identify the variables that correlate the most with CO2 emissions
print("Correlation matrix with CO2 emissions:")
print(correlation_matrix['CO2'].sort_values(ascending=False))

# Create a heatmap to visualize the correlation matrix
# Select only numeric columns for correlation calculation
numerical_df = filtered_df[numerical_columns].select_dtypes(include=['number'])
correlation_matrix = numerical_df.corr()

plt.figure(figsize=(14, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Matrix with CO2 Emissions')
plt.show()

print(correlation_matrix['CO2'].sort_values(ascending=False))

"""## **Research relationship between CO2 emissions and Consumption mix**"""

co2_col = 'CO2'  # Replace with the correct column name for CO2
# Let's assume the correct column name for consumption mix is something like 'Consumption_mix_l_per_100km'
consumption_col ='Consumption_mix(l/100km)'  # Replace with the correct column name for consumption mix

# Convert relevant columns to numerical types if they are not already
cl_union[co2_col] = pd.to_numeric(cl_union[co2_col], errors='coerce')
cl_union[consumption_col] = pd.to_numeric(cl_union[consumption_col], errors='coerce')

# Select relevant variables and drop rows with missing values in any of the important columns
filtered_df = cl_union[['brand', 'Model_file', 'Commercial_name', co2_col, consumption_col]].dropna(subset=[co2_col, consumption_col])

# Combine brand and commercial name for better labels
filtered_df['Car'] = filtered_df['brand'] + " " + filtered_df['Commercial_name']

# Create a scatter plot
plt.figure(figsize=(12, 8))

# Scatter plot for CO2 vs. Consumption_mix
scatter = plt.scatter(
    filtered_df[co2_col],
    filtered_df[consumption_col],
    alpha=0.6,
    c=filtered_df[consumption_col],  # Color by Consumption_mix for additional dimension
    cmap='viridis'
)

plt.colorbar(scatter, label='Consumption Mix (l/100km)' )
plt.xlabel('CO2 Emissions (g/km)')
plt.ylabel('Consumption_mix (l/100km)' )
plt.title('Scatter Plot of CO2 Emissions and Consumption Mix')

# Highlight the car with the highest CO2 emissions
max_co2 = filtered_df[co2_col].max()
max_co2_car = filtered_df[filtered_df[co2_col] == max_co2]
plt.scatter(max_co2_car[co2_col], max_co2_car[consumption_col], color='red', edgecolor='black', label='Highest CO2 Emitter')

# Add legend
plt.legend(loc='upper right')

# Show the plot
plt.tight_layout()
plt.show()



"""## **which cars are outliers based on carosserie and maximal engine power**"""

# Print column names to verify
print("Column names in the DataFrame:")
print(cl_union.columns.tolist())

# Correct column names based on the previous print output
# Update these variables according to your actual column names
carrosserie_col = 'Carrosserie'  # Replace with the correct column name for Carrosserie
power_col = 'power_maximal (kW)'  # Replace with the correct column name for power_maximal

# Convert relevant columns to numerical types if they are not already
cl_union[power_col] = pd.to_numeric(cl_union[power_col], errors='coerce')

# Select relevant variables and drop rows with missing values in any of the important columns
filtered_df = cl_union[[carrosserie_col, power_col]].dropna(subset=[power_col])

# Identify outliers based on power_maximal (kW)
Q1 = filtered_df[power_col].quantile(0.25)
Q3 = filtered_df[power_col].quantile(0.75)
IQR = Q3 - Q1
outliers = filtered_df[(filtered_df[power_col] < (Q1 - 1.5 * IQR)) | (filtered_df[power_col] > (Q3 + 1.5 * IQR))]

# Create a scatter plot
plt.figure(figsize=(12, 8))

# Scatter plot for power_maximal with Carrosserie as hue
sns.scatterplot(data=filtered_df, x=power_col, y=carrosserie_col, hue=carrosserie_col, palette='viridis', alpha=0.6, edgecolor='w', s=100)

# Highlight outliers with a different color and marker
plt.scatter(outliers[power_col], outliers[carrosserie_col], color='red', edgecolor='black', s=100, marker='D', label='Outliers')

plt.xlabel('Power Maximal (kW)')
plt.ylabel('Carrosserie')
plt.title('Scatter Plot of Power Maximal (kW) by Carrosserie with Outliers Highlighted')

# Show the plot
plt.legend(loc='upper right')
plt.tight_layout()
plt.show()

# Print the outliers
print("Outliers based on Power Maximal (kW):")
print(outliers)



print("Column names in the DataFrame:")
print(cl_union.columns.tolist())

# Correct column names based on the previous print output
# Update these variables according to your actual column names
carrosserie_col = 'Carrosserie'  # Replace with the correct column name for Carrosserie
power_col = 'power_maximal (kW)'  # Replace with the correct column name for power_maximal

# Convert relevant columns to numerical types if they are not already
cl_union[power_col] = pd.to_numeric(cl_union[power_col], errors='coerce')

# Select relevant variables and drop rows with missing values in any of the important columns
filtered_df = cl_union[[carrosserie_col, power_col]].dropna(subset=[power_col])

# Filter the DataFrame to include only cars with power_maximal (kW) of 180 and more
filtered_df = filtered_df[filtered_df[power_col] >= 180]

# Create a scatter plot
plt.figure(figsize=(12, 8))

# Scatter plot for power_maximal with Carrosserie as hue
sns.scatterplot(data=filtered_df, x=power_col, y=carrosserie_col, hue=carrosserie_col, palette='viridis', alpha=0.6, edgecolor='w', s=100)

plt.xlabel('Power Maximal (kW)')
plt.ylabel('Carrosserie')
plt.title('Scatter Plot of Power Maximal (kW) by Carrosserie (180 kW and above)')

# Show the plot
plt.legend(loc='upper right')
plt.tight_layout()
plt.show()

import pandas as pd


print("Column names in the DataFrame:")
print(cl_union.columns.tolist())

# Correct column names based on the previous print output
consumption_col = 'Consumption_mix(l/100km)'  # Replace with the correct column name for consumption mix

# Convert the consumption_mix (l/100km) column to numerical type if it is not already
cl_union[consumption_col] = pd.to_numeric(cl_union[consumption_col], errors='coerce')

# Filter numeric columns
numeric_columns = cl_union.select_dtypes(include=['float64', 'int64']).columns

# Calculate the correlation matrix using only numeric columns
correlation_matrix = cl_union[numeric_columns].corr()

# Display the correlation of all variables with consumption_mix (l/100km)
consumption_correlations = correlation_matrix[consumption_col].sort_values(ascending=False)
print("Correlation of variables with consumption_mix (l/100km):")
print(consumption_correlations)

# Sort the DataFrame by consumption_mix (l/100km) in descending order and select the top 20 rows
top_20_consumption_cars = cl_union.sort_values(by=consumption_col, ascending=False).head(20)

# Display the top 20 cars with the highest consumption_mix (l/100km) and relevant features
relevant_features = ['brand', 'Model_file', 'Administrative_power', 'power_maximal (kW)', 'Empty_mass_min(kg)', 'Empty_mass_max(kg)', consumption_col]
print("Top 20 cars with the highest consumption_mix (l/100km) and relevant features:")
print(top_20_consumption_cars[relevant_features])

import pandas as pd

# Assuming cl_union is the DataFrame that already contains your combined data
# Print column names to verify
print("Column names in the DataFrame:")
print(cl_union.columns.tolist())

# Correct column names based on the previous print output
co2_col = 'CO2'  # Replace with the correct column name for CO2
fuel_type_col = 'fuel_type'  # Replace with the correct column name for fuel_type

# Convert the CO2 column to numerical type if it is not already
cl_union[co2_col] = pd.to_numeric(cl_union[co2_col], errors='coerce')

# Filter the DataFrame to include only cars with CO2 emissions of 95 or lower
filtered_df = cl_union[cl_union[co2_col] <= 95]

# Display the filtered DataFrame
print("Cars with CO2 emissions of 95 or lower:")
print(filtered_df)

# Optionally, save the filtered DataFrame to a new Excel file
# filtered_df.to_excel('cars_with_co2_95_or_lower.xlsx', index=False)



# Describe the common characteristics
common_characteristics = filtered_df.describe(include='all')

# Additionally, you can analyze specific categorical columns like brand, model, and fuel type
common_brands = filtered_df['brand'].value_counts()
common_models = filtered_df['Model_file'].value_counts()
common_fuel_types = filtered_df['fuel_type'].value_counts()

print("\nMost common brands:")
print(common_brands)

print("\nMost common models:")
print(common_models)

print("\nMost common fuel types:")
print(common_fuel_types)

"""### **EMISSION TREND ANALYSIS**"""

df_cl_1['Year'] = 2012
df_cl_2['Year'] = 2013
df_cl_3['Year'] = 2014

# Standardize the column names before merging
df_cl_1.rename(columns={'Modèle dossier': 'Model_file'}, inplace=True)
df_cl_2.rename(columns={'Modèle dossier': 'Model_file'}, inplace=True)
df_cl_3.rename(columns={'Modèle dossier': 'Model_file'}, inplace=True)

cl_union = pd.concat([df_cl_1, df_cl_2, df_cl_3], axis=0, ignore_index=True)
cl_union.info()

# Group by Year and Model to get average CO2 emissions per model each year
yearly_emissions_model = cl_union.groupby(['Year', 'Model_file'])['CO2'].mean().reset_index()

# Group by Year and Carrosserie (vehicle type) to get average CO2 emissions per type each year
yearly_emissions_type = cl_union.groupby(['Year', 'Carrosserie'])['CO2'].mean().reset_index()

print(yearly_emissions_model.head())

import matplotlib.pyplot as plt

# Get the top 5 models based on the combined data
top_models = cl_union['Model_file'].value_counts().head(5).index.tolist()
print("Top models selected:", top_models)

# Filter the DataFrame for these top models
filtered_yearly_emissions = yearly_emissions_model[yearly_emissions_model['Model_file'].isin(top_models)]

# Plot the data
plt.figure(figsize=(14, 8))

for model in top_models:
    model_data = filtered_yearly_emissions[filtered_yearly_emissions['Model_file'] == model]
    plt.plot(model_data['Year'], model_data['CO2'], marker='o', label=model)

plt.xlabel('Year')
plt.ylabel('Average CO2 Emissions (g/km)')
plt.title('CO2 Emission Trends Over Time by Vehicle Model')
plt.legend(title='Vehicle Model')
plt.grid(True)
plt.show()

# Select top 5 vehicle types for simplicity
top_vehicle_types = yearly_emissions_type['Carrosserie'].value_counts().head(5).index.tolist()

plt.figure(figsize=(14, 8))

for vehicle_type in top_vehicle_types:
    type_data = yearly_emissions_type[yearly_emissions_type['Carrosserie'] == vehicle_type]
    plt.plot(type_data['Year'], type_data['CO2'], marker='o', label=vehicle_type)

plt.xlabel('Year')
plt.ylabel('Average CO2 Emissions (g/km)')
plt.title('CO2 Emission Trends Over Time by Vehicle Type')
plt.legend(title='Vehicle Type')
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt

# Group by Year and Model to get average CO2 emissions per model each year
yearly_emissions_brand = cl_union.groupby(['Year', 'brand'])['CO2'].mean().reset_index()


# Get the top 5 models based on the combined data
top_brands = cl_union['brand'].value_counts().head(10).index.tolist()
print("Top brands selected:", top_brands)

# Filter the DataFrame for these top models
filtered_yearly_emissions = yearly_emissions_brand [yearly_emissions_brand ['brand'].isin(top_brands)]

# Plot the data
plt.figure(figsize=(14, 8))

for model in top_brands:
    model_data = filtered_yearly_emissions[filtered_yearly_emissions['brand'] == model]
    plt.plot(model_data['Year'], model_data['CO2'], marker='o', label=model)

plt.xlabel('Year')
plt.ylabel('Average CO2 Emissions (g/km)')
plt.title('CO2 Emission Trends Over Time by Brand')
plt.legend(title='Brand')
plt.grid(True)
plt.show()

# Filter the data for the winning model across all years
winning_model = 'SKODA'  # Replace with the actual model name

# Filter the data for the specific model
model_data = cl_union [cl_union['brand'] == winning_model]

# Ensure that only numeric columns are aggregated
numeric_columns = model_data.select_dtypes(include=['number']).columns

# Group by 'Year' and calculate the mean for numeric columns only
spec_changes = model_data.groupby('Year')[numeric_columns].mean()

print("Technical specifications over time for the winning model:")
print(spec_changes)

# Plot the changes in key specifications
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 8))
plt.plot(spec_changes.index, spec_changes['power_maximal (kW)'], marker='o', label='Maximal Power (kW)')
plt.plot(spec_changes.index, spec_changes['Empty_mass_max(kg)'], marker='o', label='Empty Mass Max (kg)')
plt.plot(spec_changes.index, spec_changes['Administrative_power'], marker='o', label='Administrative Power')

plt.xlabel('Year')
plt.ylabel('Values')
plt.title(f'Changes in Technical Specifications for {winning_model}')
plt.legend()
plt.grid(True)
plt.show()

# List of all split columns
fuel_type_columns = [col for col in cl_union.columns if 'fuel_type_' in col]

# Function to combine them back into a single column
def combine_fuel_type(row):
    for col in fuel_type_columns:
        if row[col] == 1:
            return col.split('_')[-1]

# Apply the function to create a single 'fuel_type' column
cl_union['fuel_type'] = cl_union.apply(combine_fuel_type, axis=1)

# Now drop the split columns
cl_union = cl_union.drop(columns=fuel_type_columns)

# Verify the result
print(cl_union['fuel_type'].unique())

# Filter the data to include only SKODA vehicles
skoda_data = cl_union[cl_union['brand'] == 'SKODA']

# Group by Year and calculate the mean for numeric variables
numeric_features = ['power_maximal (kW)', 'Administrative_power', 'Empty_mass_max(kg)', 'Empty_mass_min(kg)', 'CO2']
skoda_numeric_changes = skoda_data.groupby('Year')[numeric_features].mean()

print("Numeric variables over time for SKODA:")
print(skoda_numeric_changes)

# Plot the changes in numeric variables
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 8))

for feature in numeric_features:
    if feature != 'CO2':  # Exclude CO2 from this plot, we'll analyze it separately
        plt.plot(skoda_numeric_changes.index, skoda_numeric_changes[feature], marker='o', label=feature)

plt.xlabel('Year')
plt.ylabel('Average Values')
plt.title('Changes in Numeric Variables for SKODA (2012-2014)')
plt.legend(title='Numeric Variables')
plt.grid(True)
plt.show()



# Identify the relevant categorical columns
categorical_features = ['fuel_type', 'Carrosserie', 'range', 'Gearbox']  # Replace with your actual categorical columns

# Group by Year and calculate the mode (most common value) for each categorical feature
# Handle cases where mode returns only one value
skoda_categorical_changes = skoda_data.groupby('Year')[categorical_features].agg(lambda x: x.mode()[0] if not x.mode().empty else 'Unknown') # Replace None with 'Unknown'

print("Categorical variables over time for SKODA:")
print(skoda_categorical_changes)

# Plot the changes for each categorical variable
plt.figure(figsize=(14, 6))

for feature in categorical_features:
    plt.plot(skoda_categorical_changes.index, skoda_categorical_changes[feature], marker='o', label=feature)

plt.xlabel('Year')
plt.ylabel('Category')
plt.title('Changes in Categorical Variables for SKODA (2012-2014)')
plt.legend(title='Categorical Variables')
plt.grid(True)
plt.show()

"""### ***moy-infer is a low-mid range vehicle***



# Moyenne Inférieure (moy-infer)
Segment: This typically refers to lower-middle or compact cars. These vehicles are often part of the "C-segment" in European car classification, which includes small family cars or compact cars.
Characteristics:
Size: Generally smaller in size compared to "moy-super gamme" cars, with more compact dimensions.
Price: Usually more affordable, making them accessible to a broader range of consumers.
Features: Basic to mid-range features, focusing on practicality and efficiency rather than luxury.

# Moyenne Supérieure (moy-super gamme): Larger, more expensive, and feature-rich cars, often mid-size sedans or premium vehicles.

Hence, Skoda changed their size and features to make the care more practical and efficient resulting in lower CO2 emissions
"""



"""##Numbers of cars over time"""

# Count the number of cars produced each year
production_counts = cl_union.groupby('Year').size()

print("Number of cars produced each year:")
print(production_counts)

# Plot the production counts
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.plot(production_counts.index, production_counts.values, marker='o', linestyle='-', color='blue')
plt.xlabel('Year')
plt.ylabel('Number of Cars Produced')
plt.title('Number of Cars Produced Each Year (2012-2014)')
plt.grid(True)
plt.show()



# Count the number of each car model produced across all years
model_production_counts = cl_union['Model_file'].value_counts()

print("Top 10 most produced car models:")
print(model_production_counts.head(10))

# Get the top 10 most produced models
top_10_models = model_production_counts.head(10).index



# Filter the dataset to include only the top 10 most produced models
top_models_data = cl_union[cl_union['Model_file'].isin(top_10_models)]

# Calculate the average CO2 emissions for these top models
top_models_co2 = top_models_data.groupby('Model_file')['CO2'].mean().sort_values()

print("Average CO2 emissions of the top 10 most produced car models:")
print(top_models_co2)

# Plot the CO2 emissions of the top 10 most produced models
plt.figure(figsize=(10, 6))
top_models_co2.plot(kind='bar', color='green')
plt.xlabel('Car Model')
plt.ylabel('Average CO2 Emissions (g/km)')
plt.title('Average CO2 Emissions of the Top 10 Most Produced Car Models (2012-2014)')
plt.xticks(rotation=45)
plt.grid(True)
plt.show()



import pandas as pd
import matplotlib.pyplot as plt

# Group the data by 'Year' and calculate the average CO2 emissions for each year
average_co2_per_year = cl_union.groupby('Year')['CO2'].mean()

# Display the results
print("Average CO2 emissions for each year:")
print(average_co2_per_year)

# Visualize the average CO2 emissions over the years
plt.figure(figsize=(10, 6))
plt.plot(average_co2_per_year.index, average_co2_per_year.values, marker='o', linestyle='-', color='blue')
plt.xlabel('Year')
plt.ylabel('Average CO2 Emissions (g/km)')
plt.title('Average CO2 Emissions Per Year (2012-2014)')
plt.grid(True)
plt.show()

"""### **DATA CLEANSING PREP**"""

# Step 2: Initial inspection
print(cl_union.info())  # Check data types and non-null counts
print(cl_union.describe())  # Summary statistics
print(cl_union.isnull().sum())  # Check for missing values

# Step 3: Backup the original dataset
cl_union_backup = cl_union.copy()

# Step 4: Check for duplicates
print(cl_union.duplicated().sum())

"""

>




---



 Step 5: Plan and apply data cleaning strategies
handle missing values, convert data types, drop duplicates
cl_union.drop_duplicates(inplace=True)
cl_union['date_column'] = pd.to_datetime(cl_union['date_column'])

Step 6: Segment or filter the data if needed
cl_union_filtered = cl_union[cl_union['year'] >= 2014]

Step 7: Data exploration and further cleaning
sns.histplot(cl_union['CO2'])
sns.boxplot(x=cl_union['brand'], y=cl_union['CO2'])



---


>

"""

DATA SEPARATION